/**
 * Ignore patterns per archetype. Plan B grows this into the full registry
 * (scaffold fragments and verify recipes); for now it exists so the ignores
 * are in place BEFORE the build stage writes code. Once `git add -A` runs over
 * a directory a model has been building in, whatever is not ignored is history.
 */
const COMMON = [".sfo/logs/", ".DS_Store", "*.log"];

const PYTHON = ["__pycache__/", "*.py[cod]", ".venv/", "venv/", ".pytest_cache/", ".mypy_cache/", ".ruff_cache/", "dist/", "build/", "*.egg-info/"];
const NODE = ["node_modules/", "dist/", "build/", ".turbo/", "*.tsbuildinfo"];

/**
 * The only archetype names anything may record. Exported as a tuple so the
 * spec stage's recorded choice can be validated against exactly this list: a
 * plausible-but-unregistered name ("cli-rust") has no recipe, and a build that
 * accepted one would report "no gates available" on every slice instead of
 * saying the stack was never registered.
 */
export const ARCHETYPE_NAMES = ["cli-python", "cli-node"] as const;

export type ArchetypeName = (typeof ARCHETYPE_NAMES)[number];

export function isArchetypeName(value: string): value is ArchetypeName {
  return (ARCHETYPE_NAMES as readonly string[]).includes(value);
}

/**
 * Keyed by `ArchetypeName` rather than `string`, so adding a name to
 * `ARCHETYPE_NAMES` without giving it ignores — or a recipe, below — is a
 * compile error rather than an empty gate discovered during a paid run.
 */
export const ARCHETYPES: Record<ArchetypeName, string[]> = {
  "cli-python": PYTHON,
  "cli-node": NODE,
};

/**
 * An unknown archetype gets the union, not an empty file. Being over-broad
 * costs an ignored file nobody wanted ignored; being under-broad commits a
 * virtualenv, or a scratch file holding a key.
 */
const FALLBACK = [...new Set([...PYTHON, ...NODE])];

export function gitignoreFor(archetype: string): string {
  const specific = isArchetypeName(archetype) ? ARCHETYPES[archetype] : FALLBACK;
  const header = `# generated by sfo for archetype: ${archetype}`;
  return `${[header, ...COMMON, ...specific].join("\n")}\n`;
}

/**
 * Tests that make real calls. Locked with the suite, never run by the slice
 * gate: a slice must not be graded on a network, a key, or a bill.
 *
 * Beside the test tree rather than inside it. The unit suite's fixtures exist
 * to fake exactly what a smoke test needs real: on the first project an
 * autouse fixture in tests/conftest.py set the API key to a dummy for every
 * test under tests/, and the first real smoke run was refused with a 401.
 */
export const SMOKE_DIR = "smoke";

export interface VerifyStep {
  name: string;
  command: string;
  args: string[];
  /** Whether the runner may append a path to scope this step to one slice. */
  scopeable: boolean;
  /** For a scoped step: which files are a slice's, as a `{slice}` glob (see contracts.ts). */
  files?: string;
}

/**
 * Commands are `{command, args[]}` rather than shell strings, so they run via
 * execFile with no shell. Criterion text and paths reach these commands, and a
 * quote or a semicolon in a filename must not become an injection.
 */
const RECIPES: Record<ArchetypeName, VerifyStep[]> = {
  // No --frozen on install: that flag asserts an existing, current uv.lock,
  // which is exactly what a freshly-scaffolded project lacks — and a build
  // agent legitimately adds dependencies as it works, so the lock is *meant*
  // to change. --frozen belongs in CI, not in a build in progress.
  //
  // No format gate either. Formatting is not correctness, and nothing here
  // runs a fixing pass, so a slice satisfying every criterion would fail on
  // blank lines. The build prompt asks the agent to format its own output;
  // the gate checks whether the code is right.
  "cli-python": [
    { name: "install", command: "uv", args: ["sync"], scopeable: false },
    { name: "lint", command: "uv", args: ["run", "ruff", "check", "."], scopeable: false },
    { name: "typecheck", command: "uv", args: ["run", "mypy", "--strict", "."], scopeable: false },
    { name: "test", command: "uv", args: ["run", "pytest", "-q", `--ignore=${SMOKE_DIR}`], scopeable: true, files: "tests/**/*{slice}*" },
  ],
  "cli-node": [
    { name: "install", command: "npm", args: ["ci"], scopeable: false },
    { name: "lint", command: "npm", args: ["run", "lint"], scopeable: false },
    { name: "typecheck", command: "npm", args: ["run", "typecheck"], scopeable: false },
    { name: "test", command: "npx", args: ["vitest", "run", "--exclude", `${SMOKE_DIR}/**`], scopeable: true, files: "tests/**/*{slice}*" },
  ],
};

/**
 * One smoke file, run on its own so a raised exception can be pinned to the
 * seam it came from rather than failing every seam in the run.
 */
const SMOKE_RUNNERS: Record<ArchetypeName, (file: string) => { command: string; args: string[] }> = {
  // --noconftest: outside tests/ no suite conftest applies, but one at the
  // project root would, and it could stub the very thing being checked.
  "cli-python": (file) => ({ command: "uv", args: ["run", "pytest", "-q", "--noconftest", file] }),
  "cli-node": (file) => ({ command: "npx", args: ["vitest", "run", file] }),
};

export function smokeRunnerFor(archetype: string, file: string): { command: string; args: string[] } | null {
  return isArchetypeName(archetype) ? SMOKE_RUNNERS[archetype](file) : null;
}

/**
 * An unknown archetype gets NO recipe, deliberately — the opposite of the
 * gitignore fallback. There, guessing wide costs an ignored file; here, a
 * guessed command that happens to exit 0 reports a passing gate for checks
 * that never ran. An honest gap beats a false green.
 */
export function verifyRecipeFor(archetype: string): VerifyStep[] {
  return isArchetypeName(archetype) ? RECIPES[archetype] : [];
}

/** Inspection only: reading the tree, never changing anything outside an edit. */
const READ_ONLY_COMMANDS = ["ls", "cat", "head", "tail", "grep", "find", "wc", "diff", "pwd"];

/** Looking packages and docs up from the shell. Chosen by the user over toolchain-only. */
const NETWORK_COMMANDS = ["curl"];

/**
 * `--allowedTools` for a stage. Headless `claude -p` has nobody to approve a
 * command, and user settings are not loaded, so this list is the whole of what
 * a stage may run beyond editing files in the project.
 *
 * Every stage may inspect the tree and use the web; research depends on the
 * web tools. Stages that run code also get the archetype's toolchain, derived
 * from the recipe so an agent can always run exactly what its gate will run.
 * That adds no new trust: the gate already executes the agent's code. With
 * edits only, every build agent on the first real project was denied uv,
 * pytest, ruff and mypy, and wrote code it could not run.
 */
export function agentToolsFor(archetype: string, runsCode: boolean): string[] {
  return agentToolsForCommands(runsCode ? verifyRecipeFor(archetype).map((step) => step.command) : []);
}

/** The same, for a toolchain a project declared itself. */
export function agentToolsForCommands(toolchain: string[]): string[] {
  const commands = [...new Set([...toolchain, ...READ_ONLY_COMMANDS, ...NETWORK_COMMANDS])];
  return [...commands.map((c) => `Bash(${c} *)`), "WebFetch", "WebSearch"];
}
