/**
 * Ignore patterns per archetype. Plan B grows this into the full registry
 * (scaffold fragments and verify recipes); for now it exists so the ignores
 * are in place BEFORE the build stage writes code. Once `git add -A` runs over
 * a directory a model has been building in, whatever is not ignored is history.
 */
const COMMON = [".sfo/logs/", ".DS_Store", "*.log"];

const PYTHON = ["__pycache__/", "*.py[cod]", ".venv/", "venv/", ".pytest_cache/", ".mypy_cache/", ".ruff_cache/", "dist/", "build/", "*.egg-info/"];
const NODE = ["node_modules/", "dist/", "build/", ".turbo/", "*.tsbuildinfo"];

export const ARCHETYPES: Record<string, string[]> = {
  "cli-python": PYTHON,
  "cli-node": NODE,
};

/**
 * An unknown archetype gets the union, not an empty file. Being over-broad
 * costs an ignored file nobody wanted ignored; being under-broad commits a
 * virtualenv, or a scratch file holding a key.
 */
const FALLBACK = [...new Set([...PYTHON, ...NODE])];

export function gitignoreFor(archetype: string): string {
  const specific = ARCHETYPES[archetype] ?? FALLBACK;
  const header = `# generated by sfo for archetype: ${archetype}`;
  return `${[header, ...COMMON, ...specific].join("\n")}\n`;
}

export interface VerifyStep {
  name: string;
  command: string;
  args: string[];
  /** Whether the runner may append a path to scope this step to one slice. */
  scopeable: boolean;
}

/**
 * Commands are `{command, args[]}` rather than shell strings, so they run via
 * execFile with no shell. Criterion text and paths reach these commands, and a
 * quote or a semicolon in a filename must not become an injection.
 */
const RECIPES: Record<string, VerifyStep[]> = {
  // No --frozen on install: that flag asserts an existing, current uv.lock,
  // which is exactly what a freshly-scaffolded project lacks — and a build
  // agent legitimately adds dependencies as it works, so the lock is *meant*
  // to change. --frozen belongs in CI, not in a build in progress.
  //
  // No format gate either. Formatting is not correctness, and nothing here
  // runs a fixing pass, so a slice satisfying every criterion would fail on
  // blank lines. The build prompt asks the agent to format its own output;
  // the gate checks whether the code is right.
  "cli-python": [
    { name: "install", command: "uv", args: ["sync"], scopeable: false },
    { name: "lint", command: "uv", args: ["run", "ruff", "check", "."], scopeable: false },
    { name: "typecheck", command: "uv", args: ["run", "mypy", "--strict", "."], scopeable: false },
    { name: "test", command: "uv", args: ["run", "pytest", "-q"], scopeable: true },
  ],
  "cli-node": [
    { name: "install", command: "npm", args: ["ci"], scopeable: false },
    { name: "lint", command: "npm", args: ["run", "lint"], scopeable: false },
    { name: "typecheck", command: "npm", args: ["run", "typecheck"], scopeable: false },
    { name: "test", command: "npx", args: ["vitest", "run"], scopeable: true },
  ],
};

/**
 * An unknown archetype gets NO recipe, deliberately — the opposite of the
 * gitignore fallback. There, guessing wide costs an ignored file; here, a
 * guessed command that happens to exit 0 reports a passing gate for checks
 * that never ran. An honest gap beats a false green.
 */
export function verifyRecipeFor(archetype: string): VerifyStep[] {
  return RECIPES[archetype] ?? [];
}
